import { bilateralBlur } from './bilateralBlur.js'
import { boxBlur } from './boxBlur.js'
import { convolutionPyramid } from './convolutionPyramid.js'
import { edge } from './edge.js'
import { gaussianBlur } from './gaussianBlur.js'
import { kuwahara } from './kuwahara.js'
import { laplacian } from './laplacian.js'
import { mean } from './mean.js'
import { median } from './median.js'
import { noiseBlur } from './noiseBlur.js'
import { radialBlur } from './radialBlur.js'
import { sharpen } from './sharpen.js'
export default { bilateralBlur, boxBlur, convolutionPyramid, edge, gaussianBlur, kuwahara, laplacian, mean, median, noiseBlur, radialBlur, sharpen }
