import { diffuse } from './diffuse.js'
import { envMap } from './envMap.js'
import { fakeCube } from './fakeCube.js'
import { fresnel } from './fresnel.js'
import { gooch } from './gooch.js'
import { iridescence } from './iridescence.js'
import { material } from './material.js'
import { pbrLittle } from './pbrLittle.js'
import { raymarch } from './raymarch.js'
import { specular } from './specular.js'
import { sphereMap } from './sphereMap.js'
import { sphericalHarmonics } from './sphericalHarmonics.js'
import { toMetallic } from './toMetallic.js'
import { toShininess } from './toShininess.js'
export default { diffuse, envMap, fakeCube, fresnel, gooch, iridescence, material, pbrLittle, raymarch, specular, sphereMap, sphericalHarmonics, toMetallic, toShininess }
