import { aastep } from './aastep.js'
import { bridge } from './bridge.js'
import { circle } from './circle.js'
import { cross } from './cross.js'
import { digits } from './digits.js'
import { fill } from './fill.js'
import { flip } from './flip.js'
import { hex } from './hex.js'
import { rect } from './rect.js'
import { stroke } from './stroke.js'
import { tri } from './tri.js'
export default { aastep, bridge, circle, cross, digits, fill, flip, hex, rect, stroke, tri }
