import { back } from './back.js'
import { bounce } from './bounce.js'
import { circular } from './circular.js'
import { cubic } from './cubic.js'
import { elastic } from './elastic.js'
import { exponential } from './exponential.js'
import { linear } from './linear.js'
import { quadratic } from './quadratic.js'
import { quartic } from './quartic.js'
import { quintic } from './quintic.js'
import { sine } from './sine.js'
export default { back, bounce, circular, cubic, elastic, exponential, linear, quadratic, quartic, quintic, sine }
